create
definer = root@localhost procedure UpdateBestsellers()
BEGIN
    DECLARE RENTEDCOUNT, DAYS, RNT_ID, BK_ID INT;
    DECLARE RENTSPERMONTH DECIMAL(5,2);
    DECLARE ISBESTSELLER BOOLEAN default 0;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE ALL_RENTS CURSOR FOR SELECT RENT_ID, BOOK_ID FROM RENTS;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;

OPEN ALL_RENTS;
WHILE (FINISHED = 0) DO
    FETCH ALL_RENTS INTO RNT_ID, BK_ID;
    IF (FINISHED = 0) THEN
SELECT COUNT(*) FROM RENTS
WHERE RENT_ID = RNT_ID
    INTO RENTEDCOUNT;

SELECT DATEDIFF(MAX(RENT_DATE), MIN(RENT_DATE)) + 1 FROM RENTS
WHERE RENT_ID = RNT_ID
    INTO DAYS;

SET RENTSPERMONTH = RENTEDCOUNT / DAYS * 30;
        IF (RENTSPERMONTH > 2) THEN
            SET ISBESTSELLER = TRUE;
ELSE
            SET ISBESTSELLER = FALSE;
END IF;

UPDATE BOOKS SET BESTSELLER = ISBESTSELLER
WHERE BOOK_ID = BK_ID;
COMMIT;
END IF;
END WHILE;

CLOSE ALL_RENTS;
END;

